## This Notebook Uses:

Sentences tokenization/ Words tokenization for X
Label encoding/ to categorical function of keras for y
and softmax in final layer
##### not giving desired results


In [1]:
import glob
import time
import pandas as pd
# from xml.dom import minidom
from lxml import etree
from nltk import ngrams
from nltk.tokenize import sent_tokenize
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /home/ebryx/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /home/ebryx/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /home/ebryx/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [14]:
from nltk.stem import PorterStemmer
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize 

In [2]:
t1=time.time()
path='./dataset/blogs_train/'
all_files = glob.glob(path + "/*.xml")
li = []

for filename in all_files:
  # print("file name ", filename)
  li.append(filename)
    

t2=time.time()
print("time taken to read All csv :: ", t2-t1, " seconds ")

time taken to read All csv ::  0.03780341148376465  seconds 


In [3]:
def clean_file_names(li):
  # names_list=[]
  # for i in range(len(li)):
  name_list=li.split('/')[-1]
  return name_list

In [4]:


def get_attributes_from_name(name):
  # data_object=[]
  # for data in range(len(names_list)):
  #   dummy_var=names_list[data].split('.')
  #   dummy_object={'id':dummy_var[0], 'gender':dummy_var[1],
  #                 'age':dummy_var[2], 'category':dummy_var[3],
  #                 'horoscope':dummy_var[4]
  #                 }
  #   data_object.append(dummy_object)
  dummy_var=name.split('.')
  data_object={'id':dummy_var[0], 'gender':dummy_var[1],
                  'age':dummy_var[2], 'category':dummy_var[3],
                  'horoscope':dummy_var[4]
                }
  
  return data_object



In [5]:
parser = etree.XMLParser(encoding='ISO-8859-1', recover = True, huge_tree=True)

In [6]:
def read_xml(li):
  all_objects=[]
  for i in range(len(li)):
    # print("i will run ", i+1," times")
    name_of_file=clean_file_names(li[i])
    # print(name_of_file)
    data_object=get_attributes_from_name(name_of_file)
    # print(data_object)

    post_text='  '
    tree = etree.parse(li[i], parser=parser)
    root = tree.getroot()
    for element in root.iter():
        if element.tag == 'post':
            element_text = element.text
            post_text = post_text + element_text
    mystring = post_text.replace('\n', '').replace('\r', '').replace('\t', '')
    mystring = mystring.replace('   ', '').replace('\\','')
   

#     mystring=clean_my_string(mystring)
   
    # print(mystring)
    # name_of_file=clean_file_names(li[i])
    # data_object=get_attributes_from_name(name_of_file)
    



    data_object['posts']=mystring   
    all_objects.append(data_object)

  return all_objects


In [68]:
t1=time.time()
data=read_xml(li[0:])
t2=time.time()

In [69]:
print("time taken to read :: ", (t2-t1)/100)

time taken to read ::  0.11188389539718628


In [71]:
for i in range(len(data)):
    post_of_single_person=data[i]['posts']
    
    sentences=sent_tokenize(post_of_single_person)
    
    for j in range(len(sentences)):
        words=word_tokenize(sentences[j])[:-1]
        
        sentences[j]=words
        
    data[i]['posts']=sentences
    
#     sentence=word_tokenize(sent_tokenize(post_of_single_person)[3])[:-1]
#     sentences+=sentence

In [72]:
(time.time()-t2)/100

11.726801433563232

In [73]:
df=pd.DataFrame(data)

In [74]:
df.head()

id  gender age   category    horoscope  \
0  1960525    male  15    Student        Libra   
1  3949642    male  25     indUnk          Leo   
2   688097    male  17  Education       Cancer   
3   963380    male  24    Student       Cancer   
4  4055698  female  17     indUnk  Sagittarius   

                                               posts  
0  [[i, know, ,, i, need, to, be, getting, sleep,...  
1  [[love, studying, ?, ca, n't, get, enough, of,...  
2  [[Im, currently, updating, my, site], [And, al...  
3  [[So, I, was, a, witness, to, a, pretty, nasty...  
4  [[ok, so, we, skipped, multimedia, computer, l...

In [75]:
df.tail()

id  gender age    category  horoscope  \
14595  3122872    male  15     Student      Libra   
14596  3322392  female  15      indUnk     Pisces   
14597  4008208  female  16      indUnk     Pisces   
14598  1599685    male  23     Student  Capricorn   
14599  1608709    male  25  Accounting      Aries   

                                                   posts  
14595  [[ok, we, got, webspace, off, abp, for, bgs, b...  
14596  [[dearest, diary, ,, i, do, not, know, wad, to...  
14597  [[Good, friends, are, the, greatest, treasures...  
14598  [[WE, BRING, THIS, SPECIAL, ANNOUCEMENT, TO, Y...  
14599  [[Football, Alex, 'Knight, of, the, Realm, ', ...

In [76]:


from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.model_selection import train_test_split


In [99]:
X=df['posts'].values
y=df['horoscope']

In [100]:
trainX, testX, trainY, testY = train_test_split(X,y, test_size=0.2, random_state=42)

In [128]:
for i in range(len(trainX)):
    sentences=trainX[i]
    words=''
    for j in range(len(sentences)):
        sentence=sentences[j]
        for k in range(len(sentence)):
            words+=' '+sentence[k]
    trainX[i]=words   


In [129]:
for i in range(len(testX)):
    sentences=testX[i]
    words=''
    for j in range(len(sentences)):
        sentence=sentences[j]
        for k in range(len(sentence)):
            words+=' '+sentence[k]
    testX[i]=words  

In [134]:
vectorizer = CountVectorizer()
vectorizer.fit(trainX)
X_train = vectorizer.transform(trainX)
X_test  = vectorizer.transform(testX)

In [135]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(trainY)
le.classes_

array(['Aquarius', 'Aries', 'Cancer', 'Capricorn', 'Gemini', 'Leo',
       'Libra', 'Pisces', 'Sagittarius', 'Scorpio', 'Taurus', 'Virgo'],
      dtype=object)

In [176]:
df.groupby('horoscope').first()

id  gender age              category  \
horoscope                                                
Aquarius     3386199  female  36                indUnk   
Aries        3998125    male  23                indUnk   
Cancer        688097    male  17             Education   
Capricorn    2667280  female  24  Communications-Media   
Gemini       4080749    male  15                  Arts   
Leo          3949642    male  25                indUnk   
Libra        1960525    male  15               Student   
Pisces       1822234  female  33                indUnk   
Sagittarius  4055698  female  17                indUnk   
Scorpio      3991185    male  14                indUnk   
Taurus       2747575    male  17               Student   
Virgo        1178991    male  24            Technology   

                                                         posts  
horoscope                                                       
Aquarius     [[cathartic, ramblings, -, that, 's, how, my, ...  
Aries        [[Today, was, a, good, day, for, me], [A, litt...  
Cancer       [[Im, currently, updating, my, site], [And, al...  
Capricorn    [[is, it, just, me, or, are, most, famous, peo...  
Gemini       [[ok, i, was, @, me, aunt, 's, house, ..., .an...  
Leo          [[love, studying, ?, ca, n't, get, enough, of,...  
Libra        [[i, know, ,, i, need, to, be, getting, sleep,...  
Pisces       [[what, an, end, to, my, week], [It, 's, been,...  
Sagittarius  [[ok, so, we, skipped, multimedia, computer, l...  
Scorpio      [[iN, 1885, ..., OuR, foUnDer, gAn, eNG, sEnG,...  
Taurus       [[I, watched, a, whole, 2, movies, today], [Th...  
Virgo        [[urlLink, Here, is, a, really, great, resourc...

In [181]:
y_train=le.transform(trainY)
y_test=le.transform(testY)

In [192]:
from keras.utils import np_utils

In [193]:
dummy_train_y = np_utils.to_categorical(y_train)
dummy_test_y = np_utils.to_categorical(y_test)

In [182]:
from keras.models import Sequential
from keras import layers
from keras.preprocessing.text import Tokenizer
from keras.wrappers.scikit_learn import KerasClassifier

In [224]:


input_dim = X_train.shape[1]  # Number of features

model = Sequential()
model.add(layers.Dense(20, input_dim=input_dim, activation='relu'))
model.add(layers.Dense(10,  activation='tanh'))
# model.add(layers.Flatten())
# model.add(layers.Dense(1024, activation='relu'))

model.add(layers.Dropout(0.5))
model.add(layers.Dense(12, activation='softmax'))
# model.add(Activation('softmax'))



In [225]:
X_train.shape

(11680, 696228)

In [226]:
model.compile(loss='binary_crossentropy', 
              optimizer='adam', 
              metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_34 (Dense)             (None, 20)                13924580  
_________________________________________________________________
dense_35 (Dense)             (None, 10)                210       
_________________________________________________________________
dropout_9 (Dropout)          (None, 10)                0         
_________________________________________________________________
dense_36 (Dense)             (None, 12)                132       
Total params: 13,924,922
Trainable params: 13,924,922
Non-trainable params: 0
_________________________________________________________________


In [227]:
classifier_nn = model.fit(X_train,dummy_train_y,
                    epochs=2,
                    verbose=True,
                    validation_data=(X_test, dummy_test_y),
                    batch_size=8)

Train on 11680 samples, validate on 2920 samples
Epoch 1/2
11680/11680 [==============================] - 267s 23ms/step - loss: 0.2964 - acc: 0.9163 - val_loss: 0.2867 - val_acc: 0.9167
Epoch 2/2
11680/11680 [==============================] - 280s 24ms/step - loss: 0.2868 - acc: 0.9167 - val_loss: 0.2868 - val_acc: 0.9167


In [202]:
import numpy as np

In [235]:
model.predict(X_test[100])

array([[0.07839546, 0.08526174, 0.08882953, 0.07589879, 0.0808452 ,
        0.08593997, 0.08922673, 0.08013301, 0.07589357, 0.0854533 ,
        0.08447116, 0.08965152]], dtype=float32)

In [234]:
model.predict(X_test[88])

array([[0.07839546, 0.08526174, 0.08882953, 0.07589879, 0.0808452 ,
        0.08593997, 0.08922673, 0.08013301, 0.07589357, 0.0854533 ,
        0.08447116, 0.08965152]], dtype=float32)

In [236]:
dummy_test_y[100]

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.], dtype=float32)

In [238]:
del sentences, data

In [239]:
del model

In [240]:
del X

In [241]:
del y

In [242]:
del classifier_nn

In [244]:
del df

In [246]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()
classifier.fit(X_train[:1000],y_train[:1000])
score = classifier.score(X_test[:500], y_test[:500])

/home/ebryx/anaconda3/envs/tf/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [247]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [253]:
neigh.predict(X_test[7])

array([2])

In [254]:
y_test[7]

4